setwd("/home/bingxu/spatial_metabolomics/data/mutant/")
library("Cardinal")
library("BiocParallel")
leaf_m=readMSIData("/home/bingxu/spatial_metabolomics/data/mutant/nedc_leave2-total ion count.imzML")
leafm_pre <- process(leaf_m)
mutantbaseline_corrected <- reduceBaseline(leafm_pre, method="locmin")
leaf_peaks <- peakPick(mutantbaseline_corrected,method="filter",SNR=1)
leafmutant_peaks <- peakAlign(leaf_peaks,tolerance=10, units="ppm",BPPARAM=MulticoreParam())
leafmutant_peaks=subsetFeatures(leafmutant_peaks, freq > 0.1)
mutant_nmf=NMF(leafmutant_peaks,ncomp=10)
mutant_pca=PCA(leafmutant_peaks,ncomp=10)
mutant_segmentation <- spatialShrunkenCentroids(leafmutant_peaks,
                                       weights="adaptive", r=2, k=10, s=0)
save.image("mutant.RData")
